version: '2'
services:

 web:
    image: 'bitnami/apache:latest'
    build:
     context: ./
     dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
        - ./:/var/www/html
        - ./docker/vhosts/:/etc/apache2/sites-available/
        - ./docker/vhosts/:/etc/apache2/sites-enabled/
    environment:
        - "DB_PORT=3306"
        - "DB_HOST=database"
        - "DEBIAN_FRONTEND=noninteractive"
    ports:
       - "80:80"
    links:
       - memcached
    container_name: web_container

 phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports:
       - "8181:80"
     links:
       - "database"
     environment:
       PMA_ARBITRARY: 1
       MYSQL_USER: user
       MYSQL_PASSWORD: mypassword
       MYSQL_ROOT_PASSWORD: secret
     container_name: myadmin_container

   # The Database
 database:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=secret
       - MYSQL_USER=user
       - MYSQL_PASSWORD=mypassword
       - MYSQL_DATABASE=mynewdb
     ports:
         - "33061:3306"
     container_name: db_container

 memcached:
     image: memcached:latest
     ports:
       - '11211:11211'
     environment:
       - MEMCACHED_CACHE_SIZE=128
     container_name: memcached_container

volumes:
  dbdata:
  apache_data:
      driver: local